version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/node:16.13.1
    working_directory: ~/repo
    steps:
      - checkout
      - run: cd backend && npm run install
      - run: cd backend && npm run test
workflows:
  build-and-test:
    jobs:
      - build-and-test