version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build-and-test:
    working_directory: ~/repo
    executor:
      name: node/default
    steps:
      - checkout
      - run: cd backend && npm run install
      - run: cd backend && npm run test
workflows:
  build-and-test:
    jobs:
      - build-and-test