version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/node:16.13.1
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Node Packages
          command: npm install
          path: backend
      - run:
          name: Run Tests
          command: npm run test
          path: backend
workflows:
  build-and-test:
    jobs:
      - build-and-test