version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build-and-test:
    working_directory: "~/warmup-reign/backend"
    docker:
      - image: circleci/node:16
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
        command: cd backend && npm run test
workflows:
  build-and-test:
    jobs:
      - build-and-test